### ISSUE TITLE
Docker-style identifiers

### ISSUE THREAD

**Issue by ghost** [kkuegler/human-readable-ids-java#2]
Hi!

Thanks for writing this library.

I don't know how to contact you otherwise, therefore I am doing it here.

In my private, unpublished project I wanted to use identifiers similar to the container names in Docker (like `awesome-turing`).

I came across your library and modified it (see the class `CivilizedHumanReadableIdGenerator` and the test `CivilizedHumanReadableIdGeneratorTest` in the attached archive).

Now it is possible to create both animal-related names (like `awesome-bird-31`) as well as Docker-style identifiers (like `awesome-turing-31`) using your library.

I guess my version of it is backwards compatible with yours, but I didn't test it.

Maybe you can use my code somehow. Personally I come into situations where I need unique, but human-readable/human-memorable identifiers quite often.

Best regards

Pravles Redneckoff

[2023_02_25_human-readable-ids-java.zip](https://github.com/kkuegler/human-readable-ids-java/files/10831351/2023_02_25_human-readable-ids-java.zip)

**Comment by Mixermachine** [comment]
I'm currently implementing a simular library with more words and looked at your code @pravles .
Sadly there are quite a few controversial figures in the civilizedHumans list.
The document also mentions "Ukro-American Nazis".

@kkuegler Please don't include this.
I think we should keep politics (no matter the side) out of our code.

Thanks a lot for your library @kkuegler .
If somebody is interested in mine:
https://github.com/Mixermachine/memorable-ids

**Comment by pravles** [comment]
@Mixermachine A supporter of Ukro-American Nazis is offended. How cute.

The Americans (and their German lapdogs) are, of course, not [supporting](https://thedreizinreport.com/2023/03/07/teen-suicide-and-the-barrel-again/) a regime that treats their own citizens as shit.

**Comment by Mixermachine** [comment]
@pravles Read again.
-> I think we should keep politics (**no matter the side**) out of our code.

Code has nothing to do with politics and should never be connected with war.
If you believe otherwise, do it in your own repo and mark it that way.

There are many historical figures that are not offensive for both sides.
The attempt to mix this with the current events is just unecessary and lowers the quality of the code and its result.
